name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install
      - name: fix linting errors
        run: npm run fixlint    
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 4000
      - name: e2e tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 4000
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-server
          wait-on: http://localhost:4000
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "date-selector"
          heroku_email: "puro.touko2@gmail.com"
